/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/lamp.glb 
*/
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Lamp() {
  const { nodes, materials } = useGLTF('./models/lamp.glb')

  return (
    <group dispose={null} scale={0.1}>
      <mesh
        geometry={(nodes.Object_4 as THREE.Mesh).geometry}
        material={materials.Black}
      />
      <mesh
        geometry={(nodes.Object_5 as THREE.Mesh).geometry}
        material={materials.White}
      />
    </group>
  )
}

useGLTF.preload('/lamp.glb')
